apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-appstudio/internal-services/config/crd?ref=b1149aeb02841022c763ef0254fab7d236b58253

namespace: release-service
