apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tekton-chains.yaml

images:
  - name: quay.io/konflux-ci/appstudio-utils
    digest: sha256:3320415d9cdec47fa04ae99c0e45be911e47269130b5c4fb9eda6e8c791f77aa
