apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tekton-chains.yaml

images:
  - name: quay.io/konflux-ci/appstudio-utils
    digest: sha256:8bf29c418466e79c2363d930f1b8c0acc5bdbea02a99f2026e0b21f17d8c0b35
