---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dex.yaml

images:
  - name: quay.io/konflux-ci/dex
    newName: quay.io/konflux-ci/dex
    digest: sha256:bb7c21eecd597b743846b7a7698dcc2a12bebfcd2308f9cbb9624f5499433675
